name: Generate Artifact Code

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '*'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8


    - name: Zip the code
      run: zip -r artifact.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: artifact.zip
