name: Increment Version

on:
  push:
    branches: [ master ]

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read and increment version
      run: |
        version=$(cat version.txt)
        version_num=$(echo $version | cut -d. -f3)
        new_version_num=$(($version_num + 1))
        new_version=$(echo $version | sed "s/\(.*\.\)$version_num/\1$new_version_num/")
        echo $new_version > version.txt

    - name: Commit and push version number
      run: |
        git config --local user.email "yashpal.paliwal@ap.jll.com"
        git config --local user.name "yashpal-paliwal"
        git commit -m "Increment version number" -a
        git push https://${{ secrets.PAT }}@github.com/yashpal-paliwal/devops-process-practice.git HEAD:master
