name: Build, Test, Deploy to Docker Hub - Python CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run Tests
      run: |
        pytest test_main.py
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Read version
      id: version
      run: echo "::set-output name=version::$(cat version.txt)"

    - name: Increment version
      run: echo $(($(echo ${{ steps.version.outputs.version }} | cut -d. -f3)+1)) > version.txt

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yashpalpaliwal374/test_github:${{ steps.version.outputs.version }}.TEST

    - name: Commit and push version number
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Increment version number" -a
        git push origin HEAD:master
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
