name: Deploy to Docker Hub - Python App CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run Tests
      run: |
        pytest test_main.py
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: yashpalpaliwal374/test_github:0.0.${{ github.run_number }}.TEST
    - name: Build and push Docker image
      run: |
        timestamp=$(date +%Y%m%d%H%M%S)
        docker build -t yashpalpaliwal374/test_github:0.0.$timestamp.TEST .
        docker push yashpalpaliwal374/test_github:0.0.$timestamp.TEST
